---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meds-nwproto-info
data:
  NTP_HOST: "{{ .Values.ntpserver_host }}"
  NTP_HOST_USE_IP: "{{ .Values.ntpserver_host_use_ip }}"
  SYSLOG_HOST: "{{ .Values.syslogserver_host }}"
  SYSLOG_HOST_USE_IP: "{{ .Values.syslogserver_host_use_ip }}"

---
apiVersion: v1
data:
  options: ""
kind: ConfigMap
metadata:
  name: meds-opts

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meds-cacert-info
data:
  CA_URI: "{{ .Values.hms_ca_uri }}"

